{
 "title": "Subspace-ss",
 "description": "Subspace network node and farmer dashboard",
 "tags": [ "Subspace" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "farm_id",
    "query": {
     "query": "label_values({instance=~\"$instance\"},farm_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node connections",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "subspace_established_connections{group=\"node\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Sync peers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_sync_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blocks imported",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    { "expr": "rate(subspace_node_blocks[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node P2P data rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Current P2P data rate",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total[1m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "Farmer (plotting)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Farmer connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "subspace_established_connections{group=\"farmer\", instance=~\"$instance\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Sectors downloaded total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "subspace_farmer_sector_downloaded_counter_sectors_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sectors plotted total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subspace_farmer_sector_plotted_counter_sectors_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plotted Percent",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(group) (subspace_farmer_sectors_total_sectors{state=\"Plotted\", instance=~\"$instance\", farm_id=~\"$farm_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(group) (subspace_farmer_sectors_total_sectors{state=\"NotPlotted\", instance=~\"$instance\", farm_id=~\"$farm_id\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Proving Total",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(subspace_farmer_proving_time_seconds_count{instance=~\"$instance\", farm_id=~\"$farm_id\", result=\"Success\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(subspace_farmer_proving_time_seconds_count{instance=~\"$instance\", farm_id=~\"$farm_id\", result=\"Rejected\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(subspace_farmer_proving_time_seconds_count{instance=~\"$instance\", farm_id=~\"$farm_id\", result=\"Timeout\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plotting $farm_id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "repeat": "farm_id",
   "targets": [
    {
     "expr": "subspace_farmer_sectors_total_sectors{state=\"Plotted\", instance=~\"$instance\", farm_id=\"$farm_id\"}",
     "legendFormat": "Plotted"
    },
    {
     "expr": "subspace_farmer_sectors_total_sectors{state=\"NotPlotted\", instance=~\"$instance\", farm_id=\"$farm_id\"}",
     "legendFormat": "Not plotted"
    },
    {
     "expr": "subspace_farmer_sectors_total_sectors{state=\"Expired\", instance=~\"$instance\", farm_id=\"$farm_id\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "subspace_farmer_sectors_total_sectors{state=\"AboutToExpire\", instance=~\"$instance\", farm_id=\"$farm_id\"}",
     "legendFormat": "About to expire"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "Plotted" ] },
       "reducer": {
        "params": [],
        "type": "percent_diff"
       },
       "type": "query"
      }
     ],
     "expression": "$B/($C+$B)*100",
     "reducer": "mean",
     "type": "math"
    }
   ]
  },
  {
   "title": "Sector download time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 451 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Sector encode time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 451 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Sector plot time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 459 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Sector write time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 459 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  { "title": "Farmer (farming)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 467 } },
  {
   "title": "Auditing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 468 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Proving time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 468 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  }
 ]
}